//Create a user
POST http://localhost:5000/users
Content-Type: application/json

{
    "name" : "Yeyen ad",
    "email": "yeyen@gmail.com",
    "password": "123456",
    "confPassword": "123456",
    "role": "admin"
}

###
//get All Users
GET http://localhost:5000/users

###
//Get Single User
GET http://localhost:5000/users/fc297296-e77f-4242-a977-5ff8a651c928

###
//User Update
PATCH http://localhost:5000/users/6f69c6bf-025d-4490-bffc-427bd2538bef
Content-Type: application/json

{
    "name" : "maisara",
    "email": "maisara@gmail.com",
    "password": "",
    "confPassword": "",
    "role": "user"
}

###
//delete a user
DELETE http://localhost:5000/users/fc297296-e77f-4242-a977-5ff8a651c928

###
//login user
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "yeyen@gmail.com",
    "password": "123456"
}

###
//login user
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "maisara@gmail.com",
    "password": "123456"
}

###
//me
GET http://localhost:5000/me

###
//logout
DELETE http://localhost:5000/logout


